//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoCurrencyConverterAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exchange
    {
        public int Id { get; set; }
        public string SourceCurrency { get; set; }
        public string ConvertedToCurrency { get; set; }
        public long TimeStamp { get; set; }
        public double ConversionRate { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
